- name: Install APT stuff
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - apt-transport-https
  tags:
    - docker

# - name: Install APT keys
#   apt_key: id={{ item.id}} url={{ item.url }} state=present
#   with_items:
#     - { id: '58118E89F3A912897C070ADBF76221572C52609D', url: 'hkp://p80.pool.sks-keyservers.net:80' }

- name: Add docker APT repository
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - deb https://apt.dockerproject.org/repo ubuntu-trusty main
  tags:
    - docker

- name: One more APT update
  apt: update_cache=true

- name: Uninstall outdated docker
  apt: pkg={{ item }} state=absent force=yes purge=yes
  with_items:
    - lxc-docker

- name: Install docker
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - docker-engine
  tags:
    - docker

- name: Create docker service
  template: src=templates/docker.service.j2 dest=/etc/systemd/system/docker.service group=root owner=root
  tags:
    - docker

# - name: Docker service re enable
#   shell: systemctl reenable docker.service
#   tags:
#     - docker

# - name: Docker service reload
#   shell: systemctl restart docker.service
#   tags:
#     - docker

- name: Start Docker
  service: name=docker state=restarted
  tags:
    - docker
